-- MySQL Script generated by MySQL Workbench
-- 10/17/18 00:11:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HotelBooking
-- -----------------------------------------------------
-- Client fills application, specifies places, arrival date and departure date, room class.
-- Administrator manages clients and rooms, analyzes applications and bill.

-- -----------------------------------------------------
-- Schema HotelBooking
--
-- Client fills application, specifies places, arrival date and departure date, room class.
-- Administrator manages clients and rooms, analyzes applications and bill.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelBooking` DEFAULT CHARACTER SET utf8 ;
USE `HotelBooking` ;

-- -----------------------------------------------------
-- Table `HotelBooking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `name` VARCHAR(50) NOT NULL COMMENT 'Client\'s firstname',
  `last_name` VARCHAR(75) NOT NULL COMMENT 'Client\'s lastname',
  `phone_number` CHAR(13) CHARACTER SET 'dec8' NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `wallet` BIGINT NOT NULL,
  `role` ENUM('client', 'administrator') NOT NULL,
  INDEX `LASTNAME` (`last_name` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PHONE_NUMBER` (`phone_number` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `login_UNIQUE` (`username` ASC))
ENGINE = InnoDB
COMMENT = 'Hotel\'s client';


-- -----------------------------------------------------
-- Table `HotelBooking`.`room_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`room_class` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Class id',
  `class` VARCHAR(45) NOT NULL COMMENT 'Room class',
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Contains classes of the rooms';


-- -----------------------------------------------------
-- Table `HotelBooking`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`application` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Application number',
  `places` TINYINT NOT NULL COMMENT 'Adult places that client need',
  `check_in_date` DATE NOT NULL COMMENT 'The date when client wants to arrive',
  `check_out_date` DATE NOT NULL COMMENT 'The date when client wants to departure',
  `status` ENUM('considering', 'approved', 'paid', 'expired', 'canceled') NOT NULL,
  `client_id` BIGINT NOT NULL,
  `room_class_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_application_room_class1_idx` (`room_class_id` ASC),
  INDEX `fk_application_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_application_room_class1`
    FOREIGN KEY (`room_class_id`)
    REFERENCES `HotelBooking`.`room_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_application_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `HotelBooking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Application that clients fill';


-- -----------------------------------------------------
-- Table `HotelBooking`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Room id',
  `beds` TINYINT NOT NULL COMMENT 'Beds amount',
  `status` ENUM('busy', 'free', 'reserved') NOT NULL,
  `room_class_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `BEDS` (`beds` ASC),
  INDEX `fk_room_room_class1_idx` (`room_class_id` ASC),
  CONSTRAINT `fk_room_room_class1`
    FOREIGN KEY (`room_class_id`)
    REFERENCES `HotelBooking`.`room_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Hotel\'s room';


-- -----------------------------------------------------
-- Table `HotelBooking`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HotelBooking`.`bill` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Bill id',
  `cost` DECIMAL(6,2) NOT NULL COMMENT 'Application cost',
  `room_id` INT NOT NULL,
  `application_id` BIGINT NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `application_id`, `client_id`),
  INDEX `fk_bill_room1_idx` (`room_id` ASC),
  INDEX `fk_bill_application1_idx` (`application_id` ASC, `client_id` ASC),
  CONSTRAINT `fk_bill_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `HotelBooking`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_application1`
    FOREIGN KEY (`application_id` , `client_id`)
    REFERENCES `HotelBooking`.`application` (`id` , `client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Bill for the application ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
